# Generated by Django 3.0.10 on 2020-09-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='gst_number',
            field=models.CharField(default='00ABCDEF12340Z0', editable=False, max_length=15),
        ),
    ]
