# Generated by Django 3.0.5 on 2020-09-30 18:31

from django.db import migrations, models
import django.db.models.deletion
import ecom.carousel.utils
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Unique identifier')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, max_length=255, upload_to=ecom.carousel.utils.default_upload_to, verbose_name="Carousel's image")),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='External link')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('cta_text', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'verbose_name': 'carousel',
                'verbose_name_plural': 'carousels',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='AlternativeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=ecom.carousel.utils.default_upload_to, verbose_name='image')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='External link')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('cta_text', models.CharField(blank=True, max_length=15)),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='carousel.Carousel', verbose_name='carousel')),
            ],
            options={
                'verbose_name': 'alternative image',
                'verbose_name_plural': 'alternative images',
            },
        ),
    ]
