# Generated by Django 3.0.5 on 2020-09-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativeimage',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='carousel',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
