# Generated by Django 3.0.5 on 2020-10-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_auto_20200930_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='height',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='carousel',
            name='width',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
