# Generated by Django 3.0.5 on 2020-10-15 22:17

from django.db import migrations, models
import ecom.category_nav.utils
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Unique identifier')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, max_length=255, upload_to=ecom.category_nav.utils.default_upload_to, verbose_name="Carousel's image")),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='External link')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('desc', models.CharField(blank=True, max_length=100)),
                ('cta_text', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('slug',),
            },
        ),
    ]
