# Generated by Django 3.0.5 on 2020-10-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_nav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylist',
            name='height',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='categorylist',
            name='img_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categorylist',
            name='width',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
