# Generated by Django 3.0.10 on 2020-09-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerreg', '0002_auto_20200915_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='user',
        ),
    ]
