# Generated by Django 3.0.10 on 2020-09-15 12:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sellerreg', '0006_auto_20200915_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
    ]
