# Generated by Django 3.0.10 on 2020-09-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerreg', '0008_auto_20200915_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
