# Generated by Django 3.0.10 on 2020-09-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerreg', '0009_sellerprofile_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
