# Generated by Django 3.0.5 on 2020-10-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerreg', '0010_auto_20200918_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
