# Generated by Django 3.0.5 on 2020-10-13 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sellerreg', '0011_auto_20201012_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_reg_title',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
