# Generated by Django 3.0.5 on 2020-09-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cta_text',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='banner',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
