# Generated by Django 3.0.5 on 2020-10-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20200924_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='height',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='banner',
            name='width',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
