# Generated by Django 3.0.5 on 2020-10-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_auto_20201001_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='img_only',
            field=models.BooleanField(default=False),
        ),
    ]
