# Generated by Django 3.0.10 on 2020-09-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerreg', '0003_remove_sellerprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='location',
            new_name='city',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='email_id',
            field=models.EmailField(default='testdummy@shopsafar.com', max_length=50),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
