# Generated by Django 3.0.10 on 2020-09-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerreg', '0004_auto_20200915_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='email_id',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='gst_number',
            field=models.CharField(max_length=15),
        ),
    ]
