# Generated by Django 3.0.10 on 2020-09-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerreg', '0005_auto_20200915_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='email_id',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
