# Generated by Django 3.0.10 on 2020-09-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerreg', '0007_auto_20200915_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='gst_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
